import { proto } from '../../WAProto';
import type { MediaType, SocketConfig } from '../Types';
export declare const UNAUTHORIZED_CODES: number[];
export declare const DEFAULT_ORIGIN = "https://web.whatsapp.com";
export declare const DEF_CALLBACK_PREFIX = "CB:";
export declare const DEF_TAG_PREFIX = "TAG:";
export declare const PHONE_CONNECTION_CB = "CB:Pong";
export declare const WA_DEFAULT_EPHEMERAL: number;
export declare const NOISE_MODE = "Noise_XX_25519_AESGCM_SHA256\0\0\0\0";
export declare const DICT_VERSION = 2;
export declare const KEY_BUNDLE_TYPE: Buffer<ArrayBuffer>;
export declare const NOISE_WA_HEADER: Buffer<ArrayBuffer>;
export declare const MOBILE_NOISE_HEADER: Buffer<ArrayBuffer>;
/** from: https://stackoverflow.com/questions/3809401/what-is-a-good-regular-expression-to-match-a-url */
export declare const URL_REGEX: RegExp;
export declare const WA_CERT_DETAILS: {
    SERIAL: number;
};
export declare const PROCESSABLE_HISTORY_TYPES: proto.Message.HistorySyncNotification.HistorySyncType[];
export declare const DEFAULT_CONNECTION_CONFIG: SocketConfig;
export declare const MEDIA_PATH_MAP: {
    [T in MediaType]?: string;
};
export declare const MEDIA_HKDF_KEY_MAPPING: {
    audio: string;
    document: string;
    gif: string;
    image: string;
    ppic: string;
    product: string;
    ptt: string;
    sticker: string;
    video: string;
    'thumbnail-document': string;
    'thumbnail-image': string;
    'thumbnail-video': string;
    'thumbnail-link': string;
    'md-msg-hist': string;
    'md-app-state': string;
    'product-catalog-image': string;
    'payment-bg-image': string;
    ptv: string;
};
export declare const MEDIA_KEYS: MediaType[];
export declare const MIN_PREKEY_COUNT = 5;
export declare const INITIAL_PREKEY_COUNT = 30;
export declare const DEFAULT_CACHE_TTLS: {
    SIGNAL_STORE: number;
    MSG_RETRY: number;
    CALL_OFFER: number;
    USER_DEVICES: number;
};
export declare const PHONENUMBER_MCC: {
    "1": string;
    "7": string;
    "20": string;
    "27": string;
    "30": string;
    "31": string;
    "32": string;
    "33": string;
    "34": string;
    "36": string;
    "39": string;
    "40": string;
    "41": string;
    "43": string;
    "44": string;
    "45": string;
    "46": string;
    "47": string;
    "48": string;
    "49": string;
    "51": string;
    "52": string;
    "53": string;
    "54": string;
    "55": string;
    "56": string;
    "57": string;
    "58": string;
    "60": string;
    "61": string;
    "62": string;
    "63": string;
    "64": string;
    "65": string;
    "66": string;
    "81": string;
    "82": string;
    "84": string;
    "86": string;
    "90": string;
    "91": string;
    "92": string;
    "93": string;
    "94": string;
    "95": string;
    "98": string;
    "211": string;
    "212": string;
    "213": string;
    "216": string;
    "218": string;
    "220": string;
    "221": string;
    "222": string;
    "223": string;
    "224": string;
    "225": string;
    "226": string;
    "227": string;
    "228": string;
    "229": string;
    "230": string;
    "231": string;
    "232": string;
    "233": string;
    "234": string;
    "235": string;
    "236": string;
    "237": string;
    "238": string;
    "239": string;
    "240": string;
    "241": string;
    "242": string;
    "243": string;
    "244": string;
    "245": string;
    "246": string;
    "247": string;
    "248": string;
    "249": string;
    "250": string;
    "251": string;
    "252": string;
    "253": string;
    "254": string;
    "255": string;
    "256": string;
    "257": string;
    "258": string;
    "260": string;
    "261": string;
    "262": string;
    "263": string;
    "264": string;
    "265": string;
    "266": string;
    "267": string;
    "268": string;
    "269": string;
    "290": string;
    "291": string;
    "297": string;
    "298": string;
    "299": string;
};
export declare const MOBILE_ENDPOINT = "g.whatsapp.net";
export declare const MOBILE_PORT = 443;
export declare const MOBILE_TOKEN: Buffer<ArrayBuffer>;
export declare const MOBILE_REGISTRATION_ENDPOINT = "https://v.whatsapp.net/v2";
export declare const MOBILE_USERAGENT = "WhatsApp/2.25.5.50 iOS/18.0 Device/Apple-iPhone_14";
export declare const REGISTRATION_PUBLIC_KEY: Buffer<ArrayBuffer>;
