name: Mark stale issues and pull requests

on:
  schedule:
    - cron: '30 1 * * *'
permissions:
  issues: write
  pull-requests: write
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue is stale because it has been open for 14 days with no activity. Remove the stale label or comment or this will be closed in 14 days.'
          stale-pr-message: 'This PR is stale because it has been open for 14 days with no activity. Remove the stale label or comment or this will be closed in 14 days'
          days-before-stale: 14
          days-before-close: 28
          exempt-issue-labels: 'bug,enhancement,unstale'
          exempt-pr-labels: 'bug,enhancement,unstale'
